CREATE TABLE user_account
(
    id       integer GENERATED BY DEFAULT AS IDENTITY,
    active   boolean NOT NULL,
    password varchar(255),
    username varchar(255),
    PRIMARY KEY (id)
);

CREATE TABLE user_privilege
(
    id             integer GENERATED BY DEFAULT AS IDENTITY,
    privilege_name varchar(255),
    PRIMARY KEY (id)
);

CREATE TABLE user_role
(
    id        integer GENERATED BY DEFAULT AS IDENTITY,
    role_name varchar(255),
    PRIMARY KEY (id)
);

CREATE TABLE user_role_to_privilege
(
    id           integer GENERATED BY DEFAULT AS IDENTITY,
    privilege_id integer,
    role_id      integer,
    PRIMARY KEY (id)
);

CREATE TABLE user_to_role
(
    id      integer GENERATED BY DEFAULT AS IDENTITY,
    role_id integer,
    user_id integer,
    PRIMARY KEY (id)
);

ALTER TABLE user_account
    ADD CONSTRAINT UK_castjbvpeeus0r8lbpehiu0e4 UNIQUE (username);

ALTER TABLE user_role_to_privilege
    ADD CONSTRAINT FKsile2cp4i7bg1rnketymg701u
        FOREIGN KEY (privilege_id)
            REFERENCES user_privilege;

ALTER TABLE user_role_to_privilege
    ADD CONSTRAINT FKtciumna2x6mld8vuvu4ek8fny
        FOREIGN KEY (role_id)
            REFERENCES user_role;

ALTER TABLE user_to_role
    ADD CONSTRAINT FKs8nu0ysshta6wk6i2q52pi8ip
        FOREIGN KEY (role_id)
            REFERENCES user_role;

ALTER TABLE user_to_role
    ADD CONSTRAINT FKhkt40w9qhpp3anbvc3gybnq56
        FOREIGN KEY (user_id)
            REFERENCES user_account;


